# Default Settings
[default]
gain = 0.5
loop = false
play = false

[gifs]
startup = "startup.gif"

# Create fixed tracks that don't change depending on which scene you are in
# If track.n is declared in a scene it is ignored and overriden with the below items
[fixed.7]
filename = "effect-fail-jingle.wav"
name = "Nat 1"
gain = 1.0
[fixed.8]
filename = "effect-dj-airhorn.wav"
name = "Nat 20"
gain = 1.0

# Create scenes
[scenes.tavern]
name = "Old Ivey Tavern"  # rename the scene if desired, otherwise the scene name will be displayed
[tavern.1]  # add a track
filename = "ambiance-british-pub.wav"  # specify the filename
name = "Tavern Sounds"  # change the displayed name if you want
gain = 0.6  # set a non default volume gain
loop = true  # set if the track should loop or not
play = true  # set if it should play on scene start
[tavern.2]  # add another track
filename = "music-lute-greensleeves.wav"
name = "Lute"
gain = 0.7
loop = true
[tavern.3]
filename = "effect-door-creaky.wav"

[scenes.camp]
name = "Camp"
[camp.1]
filename = "ambiance-crackling-fire.wav"
gain = 0.4
loop = true
play = true
[camp.2]
filename = "ambiance-rain-light.wav"
gain = 0.6
loop = true
[camp.3]
filename = "ambiance-rain-heavy-wind.wav"
gain = 0.8
loop = true

[scenes.stormy_woods]
name = "Stormy Woods"
[stormy_woods.1]
name = "Heavy Wind and Rain"
filename = "ambiance-rain-heavy-wind.wav"
gain = 0.4
loop = true
play = true
[stormy_woods.2]
name = "Thunderstorm"
filename = "ambiance-thunderstorm.wav"
gain = 0.6
loop = true
[stormy_woods.3]
filename = "effect-bell-tolling"
gain = 0.8
[stormy_woods.4]
filename = "effect-raven-croak.wav"
gain = 0.8
[stormy_woods.5]
filename = "effect-thunder-clap.wav"
gain = 1.0

[scenes.mine]
name = "Mine Dungeon"
[mine.1]
filename = "ambiance-water-drops.wav"
gain = 0.3
loop = true
play = true
[mine.2]
filename = "ambiance-waterfall-large.wav"
gain = 0.7
loop = true
[mine.3]
filename = "effect-door-creaky.wav"
[mine.4]
name = "Magic Success"
filename = "effect-magic-appear.wav"

# If the defalt settings are fine it can get very minimal, just a list of the file names
[scenes.battle]
name = "Battle"
gain = 1.0
tracks = ["battle-rat-battle.wav", "effect-sword-clash.wav", "effect-knife-throw.wav", "effect-arrow-shoot.wav", "effect-magic-explosion.wav"]
